from innovations.innovation import (
    LEADERSHIP_INNOVATIONS,
    MILITARY_INNOVATIONS,
    LEGISLATIVE_INNOVATIONS,
    JUDICIAL_INNOVATIONS,
    INTELLIGENCE_INNOVATIONS,
    ECONOMIC_INNOVATIONS,
    INFRASTRUCTURE_INNOVATIONS,
    RELIGIOUS_INNOVATIONS,
    CIVIC_REPRESENTATION_INNOVATIONS,
)

ROLE_INNOVATION_MAP = {
    "leadership": LEADERSHIP_INNOVATIONS,
    "military": MILITARY_INNOVATIONS,
    "legislative": LEGISLATIVE_INNOVATIONS,
    "judicial": JUDICIAL_INNOVATIONS,
    "intelligence": INTELLIGENCE_INNOVATIONS,
    "economic": ECONOMIC_INNOVATIONS,
    "infrastructure": INFRASTRUCTURE_INNOVATIONS,
    "religious": RELIGIOUS_INNOVATIONS,
    "civic_representation": CIVIC_REPRESENTATION_INNOVATIONS,
}